## Question 1

In [1]:
import numpy as np

In [2]:
a = np.arange(10,19+1)

In [3]:
b = np.linspace(1,7,10)

In [4]:
sa,sb = np.square(a), np.square(b)

In [5]:
print (sa, sb)

[100 121 144 169 196 225 256 289 324 361] [  1.           2.77777778   5.44444444   9.          13.44444444
  18.77777778  25.          32.11111111  40.11111111  49.        ]


In [6]:
print (sa + sb)

[ 101.          123.77777778  149.44444444  178.          209.44444444
  243.77777778  281.          321.11111111  364.11111111  410.        ]


In [7]:
def sum_even(arr):
    output = 0
    for i in arr:
        if i%2 == 0:
            output += i
    return output

In [8]:
sum_even(sa + sb)

588.0

In [9]:
print (np.sqrt(sa + sb))

[ 10.04987562  11.12554618  12.22474721  13.34166406  14.47219556
  15.61338457  16.76305461  17.91957341  19.08169571  20.24845673]


## Question 2

In [10]:
m = np.append(a,b).reshape(5,4)

In [11]:
print (m)

[[ 10.          11.          12.          13.        ]
 [ 14.          15.          16.          17.        ]
 [ 18.          19.           1.           1.66666667]
 [  2.33333333   3.           3.66666667   4.33333333]
 [  5.           5.66666667   6.33333333   7.        ]]


## Question 3

In [12]:
m2 = m[:,[1,2]]

In [13]:
print (m2)

[[ 11.          12.        ]
 [ 15.          16.        ]
 [ 19.           1.        ]
 [  3.           3.66666667]
 [  5.66666667   6.33333333]]


## Question 4

In [14]:
m3 = np.dot(np.transpose(m2),m)

In [15]:
print (m3)

[[ 697.33333333  748.11111111  437.88888889  482.33333333]
 [ 402.22222222  437.88888889  454.55555556  489.88888889]]


## Question 5

In [16]:
m3 = np.around(m3, decimals = 2)
print (m3)

[[ 697.33  748.11  437.89  482.33]
 [ 402.22  437.89  454.56  489.89]]


## Question 6

In [17]:
np.sort(m3, axis = None)[::-1].reshape(2,4)

array([[ 748.11,  697.33,  489.89,  482.33],
       [ 454.56,  437.89,  437.89,  402.22]])